dt:
  print_time:                         True
  print_objects_info:                 False
  record_objects_info:                True
  
  sub_image_topic:                    /usb_cam/image_rect_color
  sub_point_clouds_topic:             /pandar_points_processed
  pub_marker_topic:                   /objects
  calibration_file:                   head_camera.yaml
  
  display_image_raw:                  False
  display_image_masked:               False
  display_point_clouds_raw:           False
  display_point_clouds_projected:     False
  
  display_detection_result:           False
  display_segmentation_result:        False
  display_2d_modeling_result:         True
  display_3d_modeling_result:         True
  
  processing_mode: 'DT' # D - detection, DT - detection and tracking
  processing_object: 'both' # car, person, both
  
  pc_view_crop:                       True
  area_number:                        1
  fov_angle:                          100
  
  pc_range_crop:                      True
  sensor_height:                      2.0
  higher_limit:                       4.0
  lower_limit:                        -4.0
  min_distance:                       1.5
  max_distance:                       50.0
  
  blind_update_limit:                 5
  frame_rate:                         10
  max_id:                             10000
